#!/bin/sh

# parameters
prefix='graphene'
pseudo_c='C.pbe-n-kjpaw_psl.1.0.0.UPF'
ecutwfc=40.0
ecutrho=326.0
num_kx=8
num_ky=8
num_kz=1
num_bands=16

THIS_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "Starting ab initio calculations for $prefix..."
$ECHO 

# set quantum espresso and wannier90 paths
. qe-path
# set environment variables path
ENV_PATH=$QE_PATH/environment_variables
# set the needed environment variables
. $ENV_PATH
# override pseudopotential path
PSEUDO_DIR=$THIS_DIR/pseudo

# required executables, pseudopotentials, and directories
QE_BIN_LIST="pw.x  bands.x"
PSEUDO_LIST="$pseudo_si"
TMP_DIR="$THIS_DIR/temp"
IN_DIR="$THIS_DIR/in"
OUT_DIR="$THIS_DIR/out"

$ECHO
$ECHO "  Quantum ESSPRESSO executables directory: $BIN_DIR"
$ECHO "  Pseudopotentials directory:              $PSEUDO_DIR"
$ECHO "  Temporary directory:                     $TMP_DIR"
$ECHO "\n  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$OUT_DIR" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $OUT_DIR

# check for qe executables
for FILE in $QE_BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"

$ECHO
$ECHO "  running pw.x as:       $PW_COMMAND"
$ECHO

$ECHO "  running the scf calculation...\c"
. $IN_DIR/$prefix.scf
$PW_COMMAND < $prefix.scf.in > $prefix.scf.out
check_failure $?
$ECHO " done"

# $ECHO "  running the variable cell calculation...\c"
# . $IN_DIR/$prefix.vc
# $PW_COMMAND < $prefix.vc.in > $prefix.vc.out
# check_failure $?
# $ECHO " done"

cd $THIS_DIR
# end of file