#!/bin/sh

# parameters
prefix='graphene'
pseudo_c='C.pbe-n-kjpaw_psl.1.0.0.UPF'
ecutwfc=40.0
ecutrho=326.0
num_kx=8
num_ky=8
num_kz=1
num_bands=8

THIS_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "Starting ab initio calculations for $prefix..."
$ECHO 

# set quantum espresso and wannier90 paths
. qe-path
# set environment variables path
ENV_PATH=$QE_PATH/environment_variables
# set the needed environment variables
. $ENV_PATH
# override bin path
BIN_DIR=$QE_PATH/bin
# override pseudopotential path
PSEUDO_DIR=$THIS_DIR/pseudo

# required executables, pseudopotentials, and directories
QE_BIN_LIST="pw.x  bands.x"
PSEUDO_LIST="$pseudo_c"
TMP_DIR="$THIS_DIR/temp"
IN_DIR="$THIS_DIR/in"
OUT_DIR="$THIS_DIR/out"

$ECHO
$ECHO "  Quantum ESSPRESSO executables directory: $BIN_DIR"
$ECHO "  Pseudopotentials directory:              $PSEUDO_DIR"
$ECHO "  Temporary directory:                     $TMP_DIR"
$ECHO "\n  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$OUT_DIR" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $OUT_DIR

# check for qe executables
for FILE in $QE_BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
POST_COMMAND="$PARA_PREFIX $BIN_DIR/bands.x $PARA_POSTFIX"
PROJ_COMMAND="$PARA_PREFIX $BIN_DIR/projwfc.x $PARA_POSTFIX"

$ECHO
$ECHO "  running pw.x as:       $PW_COMMAND"
$ECHO "  running bands.x as:    $POST_COMMAND"
$ECHO "  running projwfc.x as:    $PROJ_COMMAND"
$ECHO

### band structure 

# # scf calculation
# $ECHO "  running the scf calculation...\c"
# . $IN_DIR/$prefix.scf
# $PW_COMMAND < $prefix.scf.in > $prefix.scf.out
# check_failure $?
# $ECHO " done"

# # nscf calculation
# $ECHO "  running the nscf calculation...\c"
# # increase the number of k points 
# num_kx=16
# num_ky=16
# num_kz=1
# . $IN_DIR/$prefix.nscf
# $PW_COMMAND < $prefix.nscf.in > $prefix.nscf.out
# check_failure $?
# $ECHO " done"

# # bands calculation
# $ECHO "  running the bands calculation...\c"
# . $IN_DIR/$prefix.bands
# $PW_COMMAND < $prefix.bands.in > $prefix.bands.out
# check_failure $?
# $ECHO " done"

# # post processing bands 
# $ECHO "  post processing the bands...\c"
# . $IN_DIR/$prefix.post
# $POST_COMMAND < $prefix.post.in > $prefix.post.out
# check_failure $?
# $ECHO " done"


### density of states

# scf calculation
$ECHO "  running the scf calculation...\c"
# reset the number of k points for the scf calculation 
num_kx=16
num_ky=16
num_kz=1
. $IN_DIR/$prefix.scf
# $PW_COMMAND < $prefix.scf.in > $prefix.scf.out
check_failure $?
$ECHO " done"

# nscf calculation
$ECHO "  running the nscf calculation...\c"
# increase the number of k points 
num_kx=24
num_ky=24
num_kz=1
. $IN_DIR/$prefix.nscf
$PW_COMMAND < $prefix.nscf.in > $prefix.nscf.out
check_failure $?
$ECHO " done"

# project the wavefunctions 
$ECHO "  Project wave functions...\c"
# set the energy window 
emin=-20.0
emax=10.0
. $IN_DIR/$prefix.proj
$PROJ_COMMAND < $prefix.proj.in > $prefix.proj.out
check_failure $?
$ECHO " done"


# $ECHO "  running the variable cell calculation...\c"
# . $IN_DIR/$prefix.vc
# $PW_COMMAND < $prefix.vc.in > $prefix.vc.out
# check_failure $?
# $ECHO " done"

cd $THIS_DIR
# end of file